#!/bin/bash

sudo rm -rf dist releases asciiville
cd btop
[ -f Makefile ] && make distclean
cd ../jp2a
[ -f Makefile ] && make distclean
rm -f aclocal.m4 compile config.h.in configure \
      depcomp install-sh Makefile.in missing src/Makefile.in
rm -rf autom4te.cache src/.deps 
cd ../cbftp
[ -f Makefile ] && make clean
cd ../endoh1
[ -f Makefile ] && make clobber
cd ../games/nethack
[ -f Makefile ] && make spotless
rm -f config.log config.status configure doc/Guidebook.txt \
      sys/share/Makefile.lib sys/autoconf/autoconf.hin \
      util/dgn.tab.h util/lev.tab.h
cd ../ninvaders
rm -rf cmake_build
cd ../tetris
[ -f Makefile ] && make clean
rm -f tetris gameserver src/config.h
