#!/bin/bash

sudo rm -rf dist releases asciiville
cd games/nethack
[ -f Makefile ] && make spotless
rm -f config.log config.status configure doc/Guidebook.txt \
      sys/share/Makefile.lib sys/autoconf/autoconf.hin \
      util/dgn.tab.h util/lev.tab.h
cd ../tetris
[ -f Makefile ] && make clean
rm -f tetris gameserver src/config.h
