#!/bin/bash

sudo rm -rf dist releases
cd btop
make distclean
cd ../jp2a
[ -f Makefile ] && make distclean
rm -f aclocal.m4 compile config.h.in configure \
      depcomp install-sh Makefile.in missing src/Makefile.in
rm -rf autom4te.cache src/.deps 
cd ../cbftp
make clean
cd ../diagon
rm -rf build
rm -f tools/*.jar
cd ../games/nethack
[ -f Makefile ] && make spotless
rm -f config.log config.status configure doc/Guidebook.txt sys/share/Makefile.lib
cd ../ninvaders
rm -rf cmake_build
