#!/bin/bash

arch=
centos=
debian=
fedora=

export __MPP_SRC__=`pwd`

[ -f /etc/os-release ] && . /etc/os-release
[ "${ID_LIKE}" == "debian" ] && debian=1
[ "${ID}" == "arch" ] && arch=1
[ "${ID}" == "centos" ] && centos=1
[ "${ID}" == "fedora" ] && fedora=1
[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1

if [ "${debian}" ]
then
  pkg/mkdeb.sh
else
  if [ "${arch}" ]
  then
    pkg/mkaur.sh
  else
    if [ "${centos}" ]
    then
      pkg/mkrpm.sh centos
    else
      if [ "${fedora}" ]
      then
        pkg/mkrpm.sh fedora
      else
        echo "Unsupported platform"
      fi
    fi
  fi
fi
