#!/bin/bash

[ -f VERSION ] || {
    echo "VERSION file missing. Exiting."
    exit 1
}
. ./VERSION

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates skip package creation step"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=1
while getopts "cdpu" flag; do
    case $flag in
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$CLEAN" ] && ./clean
[ "$PACKAGE" ] && ./mkpkg

cp pkg/Install-bin.sh releases/${VERSION}/Install-bin.sh
cp pkg/Uninstall-bin.sh releases/${VERSION}/Uninstall-bin.sh

ANNO="Asciiville Version ${VERSION} Release ${RELEASE}"
gittag v${VERSION}r${RELEASE} ${ANNO}

echo "Copy RPMs, Arch pkgs, and Raspberry Pi pkgs to releases/${VERSION}"

read -p "Press Enter to continue" answer

echo "Creating release for version ${VERSION} release ${RELEASE}"

gh release create v${VERSION}r${RELEASE} ${DRAFT} \
                  --title "${ANNO}" \
                  --notes-file pkg/release.md \
                  releases/${VERSION}/*

git fetch --tags origin
