#!/bin/bash

[ -f VERSION ] || {
    echo "VERSION file missing. Exiting."
    exit 1
}
. ./VERSION

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates skip package creation step"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=1
while getopts "cdpu" flag; do
    case $flag in
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$PACKAGE" ] && {
  have_arch=$(type -p makepkg)
  [ "${have_arch}" ] || {
    echo "Cannot locate makepkg"
    echo "Install Arch packaging utilites with tools/install-pacman-debian.sh"
    echo "Exiting without creating release or tags"
    exit 1
  }
}

[ "$CLEAN" ] && ./clean

ANNO="Asciiville Version ${VERSION} Release ${RELEASE}"
gittag v${VERSION}r${RELEASE} ${ANNO}
git fetch --tags origin

[ "$PACKAGE" ] && ./mkpkg

cp pkg/Install-bin.sh releases/${VERSION}/Install-bin.sh
cp pkg/Uninstall-bin.sh releases/${VERSION}/Uninstall-bin.sh

echo "Creating release for version ${VERSION} release ${RELEASE}"

gh release create v${VERSION}r${RELEASE} ${DRAFT} \
                  --title "${ANNO}" \
                  --notes-file pkg/release.md \
                  releases/${VERSION}/*
