#!/bin/bash

plat=`uname -s`
if [ "$plat" == "Darwin" ]
then
    ./macUninstall
else
  debian=
  have_apt=`type -p apt`
  have_dpkg=`type -p dpkg`
  have_rpm=`type -p rpm`
  have_yum=`type -p yum`
  [ -f /etc/os-release ] && . /etc/os-release
  [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1

  PKG=asciiville
  [ "${debian}" ] || PKG=Asciiville

  if [ "${debian}" ]
  then
    if [ "${have_apt}" ]
    then
      sudo apt remove "${PKG}" -y
    else
      if [ "${have_dpkg}" ]
      then
        sudo dpkg -r "${PKG}"
      else
        echo "Cannot locate either apt or dpkg to remove. Skipping."
      fi
    fi
  else
    if [ "${have_yum}" ]
    then
      sudo yum remove "${PKG}"
    else
      if [ "${have_rpm}" ]
      then
        sudo rpm -e "${PKG}"
      else
        echo "Cannot locate either yum or rpm to remove. Skipping."
      fi
    fi
  fi
fi
