#!/bin/bash

plat=`uname -s`
if [ "$plat" == "Darwin" ]
then
    sudo pkg/Uninstall-bin.sh
else
  debian=
  have_apt=`type -p apt`
  have_dpkg=`type -p dpkg`
  have_rpm=`type -p rpm`
  have_dnf=`type -p dnf`
  have_pac=`type -p pacman`
  [ -f /etc/os-release ] && . /etc/os-release
  [ "${ID}" == "debian" ] || [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
  [ "${arch}" ] || [ "${debian}" ] || {
    echo "${ID_LIKE}" | grep debian > /dev/null && debian=1
  }

  PKG=asciiville
  [ "${debian}" ] || [ "${arch}" ] || PKG=Asciiville

  if [ "${debian}" ]
  then
    if [ "${have_apt}" ]
    then
      sudo apt remove "${PKG}" -y
    else
      if [ "${have_dpkg}" ]
      then
        sudo dpkg -r "${PKG}"
      else
        echo "Cannot locate apt or dpkg to remove. Skipping."
      fi
    fi
  else
    if [ "${arch}" ]
    then
      if [ "${have_pac}" ]
      then
        sudo pacman -Rs "${PKG}"
      else
        echo "Cannot locate pacman to remove. Skipping."
      fi
    else
      if [ "${have_dnf}" ]
      then
        sudo dnf remove "${PKG}"
      else
        if [ "${have_rpm}" ]
        then
          sudo rpm -e "${PKG}"
        else
          echo "Cannot locate either dnf or rpm to remove. Skipping."
        fi
      fi
    fi
  fi
fi
