#!/bin/bash
# postinst script for rooncommandline
#
# see: dh_installdeb(1)
#
# set -e
#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
  configure)
    export PATH=${PATH}:/usr/local/bin:/snap/bin
    python3_inst=`type -p python3`
    if [ "${python3_inst}" ]
    then
      PYTHON="python3"
    else
      PYTHON="python"
    fi
    npm_inst=`type -p npm`
    if [ "${npm_inst}" ]
    then
      npm install -g mapscii
    fi

    lol_inst=`type -p lolcat`
    if [ ! "${lol_inst}" ]
    then
      gem_inst=`type -p gem`
      if [ "${gem_inst}" ]
      then
        wget_inst=`type -p wget`
        if [ "${wget_inst}" ]
        then
          unzip_inst=`type -p unzip`
          if [ "${unzip_inst}" ]
          then
            wget --quiet https://github.com/busyloop/lolcat/archive/master.zip
            unzip -qq master.zip
            cd lolcat-master/bin
            gem install lolcat
            cd ../..
            rm -f master.zip
            rm -rf lolcat-master
          fi
        fi
      fi
    fi

    FIGLET_DIR="/usr/local/share/figlet-fonts"
    FIGLET_ZIP="figlet-fonts.zip"
    zip_inst=`type -p zip`
    if [ "${zip_inst}" ]
    then
      pyfig_inst=`type -p pyfiglet`
      [ "${pyfig_inst}" ] || {
        ${PYTHON} -m pip install pyfiglet
        pyfig_inst=`type -p pyfiglet`
      }
      if [ "${pyfig_inst}" ]
      then
        if [ -d ${FIGLET_DIR} ]
        then
          cd ${FIGLET_DIR}
          zip -q ${FIGLET_ZIP} *.flf
          pyfiglet -L ${FIGLET_ZIP}
          rm -f ${FIGLET_ZIP}
        fi
      fi
    fi

    # Add /usr/local/bin and /usr/local/games to PATH
    if [ -d /etc/profile.d ]
    then
      if [ -f /etc/profile.d/asciiville.sh ]
      then
        echo 'export PATH=$PATH:/usr/local/bin:/usr/local/games' >> /etc/profile.d/asciiville.sh
      else
        echo 'export PATH=$PATH:/usr/local/bin:/usr/local/games' > /etc/profile.d/asciiville.sh
      fi
    else
      [ -f /etc/profile ] && {
        echo 'export PATH=$PATH:/usr/local/bin:/usr/local/games' >> /etc/profile
      }
    fi
    if [ -d /etc/zsh ]
    then
      if [ -f /etc/zsh/zshenv ]
      then
        echo 'export PATH="$PATH:/usr/local/bin:/usr/local/games"' >> /etc/zsh/zshenv
      else
        echo 'export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/games"' > /etc/zsh/zshenv
      fi
    else
      [ -f /etc/zshrc ] && {
        echo 'export PATH=$PATH:/usr/local/bin:/usr/local/games' >> /etc/zshrc
      }
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
