#!/bin/bash

FIG_FONTS="/usr/local/share/figlet-fonts"
FONT="Lean"

columns="$(tput cols)"
figlet -c -d "${FIG_FONTS}" -f "${FONT}" -k -w ${columns} "Asciiville" | tr ' _/' ' ()' | lolcat
figlet -c -d "${FIG_FONTS}" -f "${FONT}" -k -w ${columns} "Asciiville" | tr ' _/' ' ()' | cat
