post_install() {
  printf "%b\n" "${ascin}"
}

post_remove() {
  if [ -f /etc/profile.d/asciiville.sh ]
  then
    rm -f /etc/profile.d/asciiville.sh
  fi
}

read -d '' ascin <<'EOF'
Perform the following post-installation initialization:
  - Run the 'ascinit' command as your normal user (REQUIRED)

View additional post-installation configuration details at:
  - https://github.com/doctorfree/Asciiville#readme
  - https://github.com/doctorfree/Asciiville/wiki
EOF
