#!/bin/sh
# Redirect RSS feeds to fivefilters full text retrieval service
# Designed to be called as newsboat execurl, for example:
#   "exec:~/.config/newsboat/scripts/fulltextfeed https://www.tagesschau.de/xml/rss2/" 

if [ -z "$FIVE_FILTERS_SERVICE" ]; then
    FIVE_FILTERS_SERVICE=maya.local:8080
fi

if ! curl --max-time 900 -s "http://$FIVE_FILTERS_SERVICE/makefulltextfeed.php?url=$1"; then
    echo "curl command retuned non-zero code."
    exit 1
fi
