#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

channel="$1"
baseUrl="https://www.youtube.com/feeds/videos.xml"

query="$baseUrl"
[[ ! -z $channel ]] && query="$query?channel_id=$channel"


curl --fail "$query"
